### PR TITLE
feat: Port the project to TypeScript

### LINKED ISSUE #10: add TS support

### PR DESCRIPTION
**Pull request by jurca**
The source code is completely ported to TypeScript, including prettier & eslint integration, leveraging compile-time type checking where possible.

I also took the liberty to run eslint & prettier as npm test task, and run these tests as a pre-publish check.

I hope you'll like it, and if you have any feedback on how you would prefer things to be done differently, I am open to suggestions :slightly_smiling_face: .

Closes #10.

### CODE REVIEW

**Comment by tomek-f** [comment]
Thanks.
I'll rewiew over the weekend.

**Comment by tomek-f** [comment]
@jurca 
You added package-lock.json and now package-lock.json and yarn.lock are both present.

Let's remove Yarn completely. Please, remove yarn.lock file and change watch script.

**Comment by jurca** [comment]
@tomek-f Oops, my bad! Thanks for pointing this out!

I've removed the lock file and updated the watch script.

**Comment by tomek-f** [comment]
@jurca Thanks for the TS port.

**Comment by jurca** [comment]
@tomek-f Thank for review & merge! Will you, please, publish the new version to npm?

**Comment by tomek-f** [comment]
@jurca Some additional work needs to be done as v1.0.3 was released 2 years ago. https://github.com/tomek-f/simple-load-script/milestone/1

**Comment by tomek-f** [comment]
@jurca It looks like it'll be ready sooner than later.

**Comment by jurca** [comment]
@tomek-f Cool! Well, if you'd like me to help if any of those issues, I'll gladly help! (Just not sure whether those two are something you want to do yourself)

**Comment by tomek-f** [comment]
@jurca Thanks. I'll do it myself.

**Pull request merged**
